

debug: false

server:
  port: 8282
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todos?useSSL=false
    username: root
    password: root
    
  jpa:
    show-sql: true
    properties: {hibernate.dialect="org.hibernate.dialect.MySQL5Dialect"}
    
      
todo:
  prop: some-value  
      